import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/header/header";

import Nav from "../components/nav/nav";
import { pageTitle } from "../constants/constants";
//import styles from "../styles/Home.module.scss";

import "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    // <div className={styles.container}>
    <div>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />

      <div className="container">
        <h1 className="text-accent fs-500 ff-sans-cond uppercase letter-spacing-1">
          So, you want to travel to
          <span className="fs-900 ff-serif text-white">Space</span>
        </h1>
        Let’s face it; if you want to go to space, you might as well genuinely
        go to outer space and not hover kind of on the edge of it. Well sit
        back, and relax because we’ll give you a truly out of this world
        experience! Explore
      </div>
      <div></div>
    </div>
  );
};

export default Home;
